### ISSUE TITLE
Range parameter itemsToInclude

### ISSUE THREAD

**Issue by objorke** [JonasSyrstad/Stardust.Paradox#11]
**Describe the bug**

The Range extension method contains a itemsToInclude parameter, but the implementation creates a gremlin query with a range high end parameter.

http://tinkerpop.apache.org/docs/current/reference/#range-step

https://github.com/JonasSyrstad/Stardust.Paradox/blob/Main/src/Stardust.Paradox.Data/Traversals/PagingStepExtensions.cs#L21

**To Reproduce**
1. Execute a Range query with parameters (1, 1)

**Expected behavior**
1 element

**Actual behavior**
0 elements

**Comment by JonasSyrstad** [comment]
Updated the Range to have the same meaning as the gremlin spec, and added a SkipTake to simplify paging
