### ISSUE TITLE
'Has' extension doesn't allow conditions like gte

### ISSUE THREAD

**Issue by sraddhan** [JonasSyrstad/Stardust.Paradox#12]
**Describe the bug**
One of the overloaded extensions, given below, surrounds the predicate with single quote.

`public static GremlinQuery Has(this GremlinQuery queryBase, string label, string key, Func<PredicateGremlinQuery, GremlinQuery> expression)
        {
            return new ComposedGremlinQuery(queryBase, $"has('{label}','{key}','{expression.Invoke(new PredicateGremlinQuery(queryBase._connector))}')");
        }`

This doesn't allow conditions like `g.V().hasLabel('product').has('expireDate', gte(637107552000000000))`

**To Reproduce**
1. Compose a Gremlin query in C# ` var query = G.V().HasLabel(Constants.PRODUCT).Has("expireDate",q => q.Gte(DateTime.Today.AddSeconds(-1).Ticks));`
2. Debug the project and check the value of query `query.ToString()`
3. Query is rendered as `g.V().hasLabel('product').has('expireDate', 'gte(637107552000000000)')`

**Expected behavior**
`g.V().hasLabel('product').has('expireDate', gte(637107552000000000))`

**Comment by JonasSyrstad** [comment]
Hi,

Thanks for notifying. I'll push a new version later today.

**Comment by sraddhan** [comment]
Hi, Thanks Jonas. 

Seems you are not accepting PR on the repository. Realized that only after adding the code. Please let me know if you would like to review/accept PR. Thanks.

**Comment by JonasSyrstad** [comment]
Hi,

I thought that i had set the repo to allow pull requests.

I have fixed the issue and pushing a new version to nuget now

Thanx

Ps: you are welcome to contribute

/Jonas

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sraddhan** [comment]
Thanks @JonasSyrstad  for pushing new package out for `Stardust.Paradox.Data`. If I am not mistaken you will have to push the next version for the nuget package for `Stardust.Paradox.Gremlin.Providers.Gremlin` (Edit - corrected the project name) package too since it references older version of `Stardust.Paradox.Data.dll` .   Note - I tried again to push a change for the same and got "Access denied error".

**Comment by JonasSyrstad** [comment]
Hi @sraddhan,
I have not updated the provider packages when i update the two other packages (data and annotations), the only time they must be updated is when the "IGremlinLanguageConnector" changes.
Are you using the packages from .net core or .net framework?

For contributing I think you need to fork the repo, and make pull requests from there.

**Comment by sraddhan** [comment]
Thanks @JonasSyrstad !

I am using the package from .Net Standard 2.0. Could use the updated `Stardust.Paradox.Data` nuget package. Also, point noted about forking.
