### ISSUE TITLE
Vertex is not saved when it has an object property

### ISSUE THREAD

**Issue by anablsi** [JonasSyrstad/Stardust.Paradox#18]
Hi,

Kindly I need help on the following issue. I have a vertex interface defined as follows:

```
public class UserData {
   public string Name {get;set;}
   public DateTime Birthdate {get;set;}
}
```
```

[VertexLabel("user")]
public interface User : IVertex {
    string Id {get;set;}
    string PartitionKey {get;set;}

    UserData Data {get;set;}
}
```

When I create a new vertex and save it nothing is added in the graph database, but if I just don't initialize the Data property then the vertex is saved. Any suggestions how can I overcome this issue? 

Regards,
Anas.

**Comment by JonasSyrstad** [comment]
Hi,
Sorry for the late reply.
The library currently only supports primitive types: string, bool and number. 
You can make and extension to User that does serialization and store the serialized UserData in a string field. Or you can have the Name and Birthdate on the Vertex it self.

**Comment by JonasSyrstad** [comment]
By the way, in order to be able to do queries on the fields they should be on the vertex.

**Comment by anablsi** [comment]
> Hi,
> Sorry for the late reply.
> The library currently only supports primitive types: string, bool and number.
> You can make and extension to User that does serialization and store the serialized UserData in a string field. Or you can have the Name and Birthdate on the Vertex it self.

Thank you very much for your response, actually I have a more complex scenario but the sample code is just for demonstrating the case. Thank you for taking the time to answer my question.

**Comment by JonasSyrstad** [comment]
i have made a draft for this in v2.3.2, it is not as elegant as i would like it to be.

**Comment by JonasSyrstad** [comment]
Make your complex property implement IComplexProperty and override ToString
