### ISSUE TITLE
Issue with retrieving latest saved object - retrieves a stale copy of the object. 

### ISSUE THREAD

**Issue by sraddhan** [JonasSyrstad/Stardust.Paradox#19]
After saving changes with `context.SaveChangesAsync()`, the changes are being saved to the database however they are not reflected on the `GraphSet` right away. Only after restarting the function app, the changes are reflected.

**Steps to reproduce the behavior:**
1. Retrieve the object and save changes to existing GraphSet. 
`var story = await context.VAsync<IStory>(model.Id)  ?? context.CreateEntity<IStory>(model.Id);
story.Title = "Test Title";
story.SubTitle = "Test Sub Title";
await context.SaveChangesAsync();` to save changes for existing GraphSet.
2. Retrieve the same object after few minutes using the `var story = await context.Stories.GetAsync(id);`

**Expected behavior**
After 2nd retrieval object has update properties.  

**Actual behavior**
After 2nd retrieval object still contains old properties.

After restarting the Azure Function App, retrieved object is latest. 

**Additional context**
Using Azure Functions which are atomic and may scale out/in depending on the need. Is it possible that each instance of Azure Function may hold the context which don't get updated objects.

**Comment by JonasSyrstad** [comment]
I'll have a look. 


The basic behavior of the context and it's lifecycle:
It keeps all items it reads from the database in memory until it's disposed. The context should not be shared between discrete workloads. Calling Clear() will empty the trackedEntities collection, but this is dangerous when the context is shared. Only recommended when the context is used for reads and you want to force reload from the database.

Note: the concurrency model of CosmosDb may in some cases cause stale reads.

**Comment by sraddhan** [comment]
Thanks for the explanation! Surely helpful. Based on above explanation, I made few changes mainly around the scope of the `GraphContextBase`. Changed `AddScoped` to `AddTransient` while registering the class in the dependency injection module, hoping that Azure Functions get fresh copy of the `GraphContextBase` thus separating the `context` for discrete workloads. It did NOT fix the issue. Not sure if Azure Function (in consumption plan) keeps the loaded object in the memory for a while even if it's marked as `AddTransient`. 

Also, thanks for the info on concurrency model of CosmosDB. I didn't know that. However, this doesn't seem to be the issue. Reason: After updating the value, making a `get` call after couple of minutes where `Azure Function` still returns stale data.

**Comment by JonasSyrstad** [comment]
I'm not that familliar with Azure Functions, at least not at the level where i can guide you on this. 
I have done some test related to this and as far as I can tell the context is behaving as designed.

**Comment by sraddhan** [comment]
Thanks for checking this at your end. I used `.clear()` and at least now I see the updated values right away. Yet to find out how this will behave with concurrent reads and writes.

**Comment by sraddhan** [comment]
Ran few tests. I have not seen any error with 20K read requests (10 concurrent at a time) and a few write requests. I see the element being udpated and return successfully. It's hard to say if any of those get calls had bad/partial data (even thought it was http 200 OK) right when update operation was in progress. But the original issue of stale data seems to be resolved. I will close this issue. Thanks again for the info and  checking.
