### ISSUE TITLE
Sending partitionKey to cosmos while creating a Vertex

### ISSUE THREAD

**Issue by Nitin2392** [JonasSyrstad/Stardust.Paradox#20]
Microsoft has now made it mandatory to create a Vertex inside a graph with a `partitionKey`. I have defined a `_partitionKey` property in Azure for the Vertex. How do I send a value for this from my `Stardust.Paradox` model ? 

I have a method that uses an implementation of a class that derives the `GraphContextBase`. So before doing `context.SaveChangesAsync`, I need to set the partitionKey value. I tried using `context.GetOrCreate<T>(ID, "_partitionKey") and defined a property for `PartitionKey` in the `T` class but that didn't seem to initialize anything. 

Would appreciate some help in this regard 👍

**Comment by Nitin2392** [comment]
Never mind. I added it as a property and it worked 👍

**Comment by JonasSyrstad** [comment]
Cool. Was just about to reach out to you. 

Please feel free to contact me if you have other questions or sugestion on how to make the tool better

/Jonas
