### ISSUE TITLE
GremlinFactory.Or function needs two expressions

### ISSUE THREAD

**Issue by Nitin2392** [JonasSyrstad/Stardust.Paradox#24]
Thanks for the awesome work you are doing with this library @JonasSyrstad. 

In the `PredicateExtension.cs` file, I see that the `Or()` exists but why does it exist with only one expression ? The Gremlin API supports writing `Or()` as such - 

`G.V().Has("key",value).Or(condition1, condition 2)` but it looks like `Stardust.Paradox` doesn't support two expressions ? 

I'd love to see this feature included with the library.

**Comment by JonasSyrstad** [comment]
Thank you for reporting this. I think there might be more steps and permutations of them that is missing. Keep reporting them as you run discover them and I'll try my best to add them as we go :)

**Comment by JonasSyrstad** [comment]
included in Stardust.Paradox.Data 2.1.6

**Comment by Nitin2392** [comment]
Thank you Jonas :) Highly appreciate your efforts!
