### ISSUE TITLE
Issue with updating vertex properties to `null` using `context.SaveChangesAsync` 

### ISSUE THREAD

**Issue by Nitin2392** [JonasSyrstad/Stardust.Paradox#26]
Hey @JonasSyrstad. I ran into this weird bug and would like to understand if there's a possible workaround for this. 

I'm trying to update an existing Graph Vertex with updated properties. Some properties have been set to `null`. But when I run `await context.SaveChangesAsync()`, the `null` properties don't get updated. The ones which have a non-null value do get updated. 

Here's a code snippet explaining creation and updation.

```
public interface IObj : Ivertex 
{
string name {get;set};
DateTime? someDate {get;set}
}

public SomeFunc(GraphContext context, string id)
{
var foo = await context.Obj.GetAsync(id) ?? context.CreateEntity<IObj>(id);

foo.name = "Test";
foo.someDate = null;

await context.SaveChangesAsync();
}
``` 
Now, the above method works perfectly during the object creation process (i.e if the ID doesn't exist in the Graph DB). However, while I invoke this method to update and say, assign one of the properties to `null` and make the `context.SaveChangesAsync` call, it doesn't seem to acknowledge the fact that I'm changing the property value to `null` and instead, retains it's origin non-null value. 
I tried setting the property to `null` in the Cosmos Graph DB directly and that worked - which means that the Graph DB does accept `null` for `string`, and `number` properties but somehow, the update using `context.SaveChangesAsync` doesn't seem to run as expected. 

Any thoughts on this issue would be more than welcome @JonasSyrstad

**Comment by Nitin2392** [comment]
Update : I saw this StackOverFlow answer  https://stackoverflow.com/questions/55864376/gremlin-how-to-overcome-property-null-problem-and-write-a-query-which-updates-a

... and I believe these issues may be linked. While the top answer does mention that TinkerPop doesn't support setting property values to `null`, it looks like it does now since I was able to set a property value to `null` from the Cosmos DB Data Explorer in Azure by running this Gremlin Query - 

`G.V(id).property('propertyName',null)`

But when I try running the exact same query through Stardust.Paradox like so, 

`G.V(id).Property('propertyName', (DateTime)? null)`, I get an `Object reference not set to an Object` exception which probably is because `null` isn't being accepted in the second parameter. Would it be possible for you to add the feature to set `property` values to `null` ?

**Comment by JonasSyrstad** [comment]
Hi @Nitin2392 
TinkerPop it self does not support 'null' in properties, but some implementations may support it. Since its not supported by TinkerPop, Gremlin.Net does not allow this in paramertized queries. I am working on a fix that passes the set property to null as a unparametrized query element. 
I'll close the issue when the update is published to nuget.

Thanx for reporting this issue.

**Comment by Nitin2392** [comment]
Thanks @JonasSyrstad. Appreciate the help.

**Comment by JonasSyrstad** [comment]
Pushed new version now. Sorry for the wait, been totally crazy at work the last weeks.
